FROM python:3.11-alpine

WORKDIR /worker

RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-client \
    libpq-dev \
    ca-certificates

COPY worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini /worker/alembic.ini
COPY alembic/ /worker/alembic/

COPY worker/ /worker/

CMD ["python", "main.py"]
