FROM python:3.11-alpine

WORKDIR /worker

RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-client \
    libpq-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
